GLOBAL_MAPPER_SCRIPT VERSION=1.00

UNLOAD_ALL

SET_LOG_FILE FILENAME="%(logFile)s"

IMPORT FILENAME="%(dataFile)s" ANTI_ALIAS=YES

SET_VERT_DISP_OPTS SHADER_NAME="%(renderName)s" ENABLE_HILL_SHADING=YES

EXPORT_RASTER  FILENAME="%(outputFile)s" TYPE=GEOTIFF USE_LZW=YES

UNLOAD_ALL

